services:
  _defaults:
    autoconfigure: true

  DWenzel\Reporter\:
    resource: '../Classes/*'

  DWenzel\Reporter\Backend\ToolbarItems\SystemInformationSlot:
    tags:
      - name: event.listener
        identifier: 'dwenzel-reporter-system-information'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
